[package]
name = "dialogue_system"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
bevy_rapier3d = "0.31.0"
rand = "0.9.2"
rng = "0.1.0"

#[profile.dev]
#opt-level = 1

#[profile.dev.package."*"]
#opt-level = 3
